vich_uploader:
    db_driver: orm

    mappings:
        objetCuls:
            uri_prefix: /images/objetCuls
            upload_destination: '%kernel.project_dir%/public/images/objetCuls'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
